# espanso configuration file

# https://espanso.org/docs/
# https://github.com/calrobertlee/bear-app-mods/blob/24e25f017909148dcda05af0bdf19b9884065352/default.yml

matches:
  ######################### Other ###########################
  - trigger: ":flip"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: ":idk"
    replace: "¯\\_(ツ)_/¯"

  ######################### Other ###########################
  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
